import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    mcp: "src/mcp/index.ts",
    "bridges-whiteboard": "src/bridges/whiteboard.ts",
    "bridges-artboard": "src/bridges/artboard.ts",
    "bridges-flow": "src/bridges/flow.ts",
    "bridges-forms": "src/bridges/forms.ts",
    "bridges-sheets": "src/bridges/sheets.ts",
    "bridges-code": "src/bridges/code.ts",
    "bridges-charts": "src/bridges/charts.ts",
    "bridges-scene": "src/bridges/scene.ts",
    "bridges-screens": "src/bridges/screens.ts",
    "bridges-slides": "src/bridges/slides.ts",
    "sheets-adapter": "src/sheets-adapter.ts",
    "components-shared-whiteboard": "src/components/SharedWhiteboard/index.ts",
    sharing: "src/sharing/index.ts",
    presence: "src/presence/index.ts",
    undo: "src/undo/index.ts",
    "relay-server": "src/relay-server/index.ts",
    "relay-server-cli": "src/relay-server/cli.ts",
    styles: "src/styles.css",
  },
  format: ["esm", "cjs"],
  dts: {
    entry: [
      "src/index.ts",
      "src/mcp/index.ts",
      "src/bridges/whiteboard.ts",
      "src/bridges/artboard.ts",
      "src/bridges/flow.ts",
      "src/bridges/forms.ts",
      "src/bridges/sheets.ts",
      "src/bridges/code.ts",
      "src/bridges/charts.ts",
      "src/bridges/scene.ts",
      "src/bridges/screens.ts",
      "src/bridges/slides.ts",
      "src/sheets-adapter.ts",
      "src/components/SharedWhiteboard/index.ts",
      "src/sharing/index.ts",
      "src/presence/index.ts",
      "src/undo/index.ts",
      "src/relay-server/index.ts",
    ],
  },
  sourcemap: true,
  clean: true,
  external: [
    "react",
    "react-dom",
    "@particle-academy/fancy-auto-common",
    "@particle-academy/fancy-whiteboard",
    "@particle-academy/fancy-artboard",
    "@particle-academy/fancy-flow",
    "@particle-academy/fancy-sheets",
    "@particle-academy/fancy-slides",
  ],
  treeshake: true,
});
