import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    mcp: "src/mcp/index.ts",
    "bridges-whiteboard": "src/bridges/whiteboard.ts",
    "bridges-flow": "src/bridges/flow.ts",
    "bridges-forms": "src/bridges/forms.ts",
    "bridges-sheets": "src/bridges/sheets.ts",
    "bridges-code": "src/bridges/code.ts",
    "bridges-charts": "src/bridges/charts.ts",
    "bridges-scene": "src/bridges/scene.ts",
    "bridges-screens": "src/bridges/screens.ts",
    "sheets-adapter": "src/sheets-adapter.ts",
    sharing: "src/sharing/index.ts",
    presence: "src/presence/index.ts",
    undo: "src/undo/index.ts",
    styles: "src/styles.css",
  },
  format: ["esm", "cjs"],
  dts: {
    entry: [
      "src/index.ts",
      "src/mcp/index.ts",
      "src/bridges/whiteboard.ts",
      "src/bridges/flow.ts",
      "src/bridges/forms.ts",
      "src/bridges/sheets.ts",
      "src/bridges/code.ts",
      "src/bridges/charts.ts",
      "src/bridges/scene.ts",
      "src/bridges/screens.ts",
      "src/sheets-adapter.ts",
      "src/sharing/index.ts",
      "src/presence/index.ts",
      "src/undo/index.ts",
    ],
  },
  sourcemap: true,
  clean: true,
  external: ["react", "react-dom", "@particle-academy/fancy-whiteboard"],
  treeshake: true,
});
