// MCPB (Claude Desktop "Extensions" bundle) manifest + proxy generation.
//
// PURE — no filesystem, no child_process — so it's trivially testable. The
// `writeMcpbBundle` Node helper (./build) layers fs + the official mcpb CLI on
// top of these.
//
// The hard fact MCPB forces on you: it is STDIO-ONLY. The manifest's
// `server.type` is one of `node` / `python` / `binary` / `uv` — there is no
// `type: "http"`. So to bundle a REMOTE MCP server (what fancy-* apps almost
// always are) you ship a thin `node` server whose `mcp_config` runs
// `npx -y mcp-remote <url>`, bridging stdio→HTTP. The manifest validator still
// requires `entry_point`, so an (otherwise unused) proxy stub is emitted too.
//
// Future-proof: when MCPB grows a real `type: "http"`, drop the proxy and point
// straight at the URL — the call site here doesn't change.

/** The MCPB manifest schema version this helper emits. */
export const MCPB_MANIFEST_VERSION = "0.2";

/** Minimum Node the mcp-remote proxy needs on the user's machine. */
export const MCPB_MIN_NODE = ">=18.0.0";

/** A tool advertised in the bundle manifest (display-only metadata). */
export interface McpbTool {
  name: string;
  description?: string;
}

/** Inputs for {@link buildMcpbManifest} / `writeMcpbBundle`. */
export interface McpbManifestInput {
  /** Machine name, e.g. `"decksmith"` (lowercase, no spaces). */
  name: string;
  /** Human display name, e.g. `"Decksmith"`. Defaults to `name`. */
  display_name?: string;
  /** Bundle version, e.g. `"0.2.0"`. */
  version: string;
  /** Short one-line description. */
  description: string;
  /** Optional longer description shown on the extension's detail view. */
  long_description?: string;
  author: { name: string; url?: string; email?: string };
  homepage?: string;
  documentation?: string;
  support?: string;
  /** The remote MCP endpoint the bundle proxies to. */
  mcpUrl: string;
  /** Advertised tools (display metadata only). */
  tools?: McpbTool[];
  keywords?: string[];
  license?: string;
  /** Entry-point path inside the bundle. Defaults to `"server/proxy.js"`. */
  entryPoint?: string;
}

/** The default entry-point path the proxy stub is written to. */
export const DEFAULT_MCPB_ENTRY_POINT = "server/proxy.js";

/**
 * Build the full MCPB `manifest.json` object for a remote MCP server, wrapping
 * it with `npx -y mcp-remote <url>` (stdio→HTTP). Returns a plain object ready
 * to `JSON.stringify`.
 */
export function buildMcpbManifest(
  input: McpbManifestInput,
): Record<string, unknown> {
  const entryPoint = input.entryPoint ?? DEFAULT_MCPB_ENTRY_POINT;
  return {
    manifest_version: MCPB_MANIFEST_VERSION,
    name: input.name,
    display_name: input.display_name ?? input.name,
    version: input.version,
    description: input.description,
    ...(input.long_description
      ? { long_description: input.long_description }
      : {}),
    author: input.author,
    ...(input.homepage ? { homepage: input.homepage } : {}),
    ...(input.documentation ? { documentation: input.documentation } : {}),
    ...(input.support ? { support: input.support } : {}),
    server: {
      type: "node",
      entry_point: entryPoint,
      mcp_config: {
        command: "npx",
        args: ["-y", "mcp-remote", input.mcpUrl],
      },
    },
    tools: input.tools ?? [],
    tools_generated: false,
    prompts_generated: false,
    ...(input.keywords ? { keywords: input.keywords } : {}),
    license: input.license ?? "MIT",
    compatibility: {
      claude_desktop: ">=0.10.0",
      platforms: ["darwin", "win32", "linux"],
      runtimes: { node: MCPB_MIN_NODE },
    },
  };
}

/**
 * The `server/proxy.js` stub. MCPB requires an `entry_point` file even though
 * `mcp_config.command` overrides it; if it ever DOES run, it spawns
 * `npx -y mcp-remote <url>` itself so the bundle still works.
 */
export function buildMcpbProxyStub(mcpUrl: string): string {
  // JSON.stringify gives us a safely-quoted JS string literal for the URL.
  const urlLiteral = JSON.stringify(mcpUrl);
  return `#!/usr/bin/env node
// MCPB proxy shim (generated by @particle-academy/agent-integrations).
//
// MCPB (Claude Desktop Extensions) only supports local stdio servers, but this
// MCP server is a remote HTTP endpoint. The manifest's \`mcp_config\` invokes
// \`npx -y mcp-remote <url>\` to bridge the gap — this file is the entry_point
// fallback the manifest validator requires. If you're seeing this run,
// mcp_config wasn't honored; spawn mcp-remote directly so the bundle still works.

const { spawn } = require("node:child_process");

const url = ${urlLiteral};
const child = spawn("npx", ["-y", "mcp-remote", url], { stdio: "inherit" });

child.on("exit", (code) => process.exit(code ?? 0));
process.on("SIGINT", () => child.kill("SIGINT"));
process.on("SIGTERM", () => child.kill("SIGTERM"));
`;
}
